### ISSUE TITLE
Time is running out.

### ISSUE THREAD

**Issue by karthik-madhamanchi** [ironmaniiith/mi.com.hack#1]
Hello sir , I'm Karthi i follow you trick for playing mi pair to win game. After the 40th level time is running out. Is there any solution for this problem? if you have a solution. please share to me.

**Comment by ironmaniiith** [comment]
There are various things in the description of the video that I uploaded on youtube, I have discussed many more things, improvements and all with the other users, make sure you see them.

https://www.youtube.com/watch?v=uyOmX0g6jMg
https://www.youtube.com/watch?v=N1l2QJGQHEo

**Comment by Bhavya1705** [comment]
Sir,
on entering the code this gets displayed "Uncaught SyntaxError: Unexpected token var"
Please see to my request. thankyou .
P.S tomorrow is the last day.

**Comment by ironmaniiith** [comment]
Make sure you go through the description below the video very well, I have mentioned everything very carefully there, many people were not doing it correctly, hence they were facing problems.
Which browser are you using?
And can you send me a screenshot of the error.?

**Comment by ironmaniiith** [comment]
This might interest you a lot :wink: 
https://www.youtube.com/watch?v=cL-XWX_8yIU

**Comment by Bhavya1705** [comment]
Thanks
