### ISSUE TITLE
VM734:45 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null(…)

### ISSUE THREAD

**Issue by suri9160** [ironmaniiith/mi.com.hack#2]
VM734:45 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null(…)

**Comment by saurabhiiit** [comment]
@suri9160 click on the board when the game starts and then do inspect element  and then do to console 
I hope it will work then

**Comment by ironmaniiith** [comment]
@suri9160 , Make sure you go through the description of both the videos uploaded on youtube well.
You need to play at a different url to make this work.

This is where you need to play
http://mobile.mi.com/in/events/2ndanniversary/playgame/

**Comment by karthik-madhamanchi** [comment]
you better to run it in crome browser..

**Comment by ironmaniiith** [comment]
@suri9160 , I am assuming that you have solved this and hence closing this issue.
